//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp.API
{
    using OfflineSync.DomainModel.Models;
    using System;
    using System.Collections.Generic;

    public partial class Testtbl : ISyncBaseModel
    {
        public string VersionID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    }
}
